version: '3.8'

services:
  # Neo4j Graph Database
  neo4j:
    image: neo4j:5.14-community
    container_name: rag-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - rag-network

  # PostgreSQL with pgvector
  postgres:
    image: ankane/pgvector:latest
    container_name: rag-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=rag_user
      - POSTGRES_PASSWORD=rag_password
      - POSTGRES_DB=rag_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rag-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: rag-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - rag-network

volumes:
  neo4j_data:
  neo4j_logs:
  postgres_data:
  redis_data:

networks:
  rag-network:
    driver: bridge